labelPRBasedOnFilePath:
  need review:
    - "ZHTWPack/**"

  kubejs:
    - "ZHTWPack/kubejs/**"

  resource:
    - "ZHTWPack/kubejs/assets/**"
    - "ZHTWPack/config/fancymenu/**"

  ftbquest:
    - "ZHTWPack/config/ftbquests/**"
    - "ZHTWPack/kubejs/assets/ftbquests**"

labelerFlags:
    labelOnPRUpdates: true  

firstPRWelcomeComment: >
  - 請確認此 Pull Request 的目標分支是否正確
  - 請確認此 Pull Request 的狀態，若未完成，請設置為 Draft
  - 劣質的機器翻譯請不要輕易提交，但是機翻潤色是允許的
  - 請耐心等待審核，審核完成後請及時前來處理
